server.port=8083
spring.application.name=event-service

spring.data.mongodb.uri=mongodb://localhost:27017/eventdb

# URLs for inter-service calls (optional, for validation)
student.service.url=http://localhost:8081
faculty.service.url=http://localhost:8082